// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: quicksilver/interchainstaking/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryZonesInfoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryZonesInfoRequest) Reset()         { *m = QueryZonesInfoRequest{} }
func (m *QueryZonesInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryZonesInfoRequest) ProtoMessage()    {}
func (*QueryZonesInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{0}
}
func (m *QueryZonesInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryZonesInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryZonesInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryZonesInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryZonesInfoRequest.Merge(m, src)
}
func (m *QueryZonesInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryZonesInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryZonesInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryZonesInfoRequest proto.InternalMessageInfo

func (m *QueryZonesInfoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryZonesInfoResponse struct {
	Zones      []Zone              `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryZonesInfoResponse) Reset()         { *m = QueryZonesInfoResponse{} }
func (m *QueryZonesInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryZonesInfoResponse) ProtoMessage()    {}
func (*QueryZonesInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{1}
}
func (m *QueryZonesInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryZonesInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryZonesInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryZonesInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryZonesInfoResponse.Merge(m, src)
}
func (m *QueryZonesInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryZonesInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryZonesInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryZonesInfoResponse proto.InternalMessageInfo

func (m *QueryZonesInfoResponse) GetZones() []Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *QueryZonesInfoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDepositAccountForChainRequest is the request type for the
// Query/InterchainAccountAddress RPC
type QueryDepositAccountForChainRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty" yaml:"chain_id"`
}

func (m *QueryDepositAccountForChainRequest) Reset()         { *m = QueryDepositAccountForChainRequest{} }
func (m *QueryDepositAccountForChainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDepositAccountForChainRequest) ProtoMessage()    {}
func (*QueryDepositAccountForChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{2}
}
func (m *QueryDepositAccountForChainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDepositAccountForChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDepositAccountForChainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDepositAccountForChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDepositAccountForChainRequest.Merge(m, src)
}
func (m *QueryDepositAccountForChainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDepositAccountForChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDepositAccountForChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDepositAccountForChainRequest proto.InternalMessageInfo

func (m *QueryDepositAccountForChainRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

// QueryDepositAccountForChainResponse the response type for the
// Query/InterchainAccountAddress RPC
type QueryDepositAccountForChainResponse struct {
	DepositAccountAddress string `protobuf:"bytes,1,opt,name=deposit_account_address,json=depositAccountAddress,proto3" json:"deposit_account_address,omitempty" yaml:"deposit_account_address"`
}

func (m *QueryDepositAccountForChainResponse) Reset()         { *m = QueryDepositAccountForChainResponse{} }
func (m *QueryDepositAccountForChainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDepositAccountForChainResponse) ProtoMessage()    {}
func (*QueryDepositAccountForChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{3}
}
func (m *QueryDepositAccountForChainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDepositAccountForChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDepositAccountForChainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDepositAccountForChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDepositAccountForChainResponse.Merge(m, src)
}
func (m *QueryDepositAccountForChainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDepositAccountForChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDepositAccountForChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDepositAccountForChainResponse proto.InternalMessageInfo

func (m *QueryDepositAccountForChainResponse) GetDepositAccountAddress() string {
	if m != nil {
		return m.DepositAccountAddress
	}
	return ""
}

type QueryDelegatorIntentRequest struct {
	ChainId          string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty" yaml:"chain_id"`
	DelegatorAddress string `protobuf:"bytes,2,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
}

func (m *QueryDelegatorIntentRequest) Reset()         { *m = QueryDelegatorIntentRequest{} }
func (m *QueryDelegatorIntentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDelegatorIntentRequest) ProtoMessage()    {}
func (*QueryDelegatorIntentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{4}
}
func (m *QueryDelegatorIntentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegatorIntentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegatorIntentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegatorIntentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegatorIntentRequest.Merge(m, src)
}
func (m *QueryDelegatorIntentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegatorIntentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegatorIntentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegatorIntentRequest proto.InternalMessageInfo

func (m *QueryDelegatorIntentRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *QueryDelegatorIntentRequest) GetDelegatorAddress() string {
	if m != nil {
		return m.DelegatorAddress
	}
	return ""
}

type QueryDelegatorIntentResponse struct {
	Intent *DelegatorIntent `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
}

func (m *QueryDelegatorIntentResponse) Reset()         { *m = QueryDelegatorIntentResponse{} }
func (m *QueryDelegatorIntentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDelegatorIntentResponse) ProtoMessage()    {}
func (*QueryDelegatorIntentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{5}
}
func (m *QueryDelegatorIntentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegatorIntentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegatorIntentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegatorIntentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegatorIntentResponse.Merge(m, src)
}
func (m *QueryDelegatorIntentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegatorIntentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegatorIntentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegatorIntentResponse proto.InternalMessageInfo

func (m *QueryDelegatorIntentResponse) GetIntent() *DelegatorIntent {
	if m != nil {
		return m.Intent
	}
	return nil
}

type QueryDelegationsRequest struct {
	ChainId    string             `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty" yaml:"chain_id"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegationsRequest) Reset()         { *m = QueryDelegationsRequest{} }
func (m *QueryDelegationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDelegationsRequest) ProtoMessage()    {}
func (*QueryDelegationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{6}
}
func (m *QueryDelegationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegationsRequest.Merge(m, src)
}
func (m *QueryDelegationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegationsRequest proto.InternalMessageInfo

func (m *QueryDelegationsRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *QueryDelegationsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDelegationsResponse struct {
	Delegations []Delegation        `protobuf:"bytes,1,rep,name=delegations,proto3" json:"delegations"`
	Tvl         int64               `protobuf:"varint,2,opt,name=tvl,proto3" json:"tvl,omitempty"`
	Pagination  *query.PageResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegationsResponse) Reset()         { *m = QueryDelegationsResponse{} }
func (m *QueryDelegationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDelegationsResponse) ProtoMessage()    {}
func (*QueryDelegationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{7}
}
func (m *QueryDelegationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegationsResponse.Merge(m, src)
}
func (m *QueryDelegationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegationsResponse proto.InternalMessageInfo

func (m *QueryDelegationsResponse) GetDelegations() []Delegation {
	if m != nil {
		return m.Delegations
	}
	return nil
}

func (m *QueryDelegationsResponse) GetTvl() int64 {
	if m != nil {
		return m.Tvl
	}
	return 0
}

func (m *QueryDelegationsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryWithdrawalRecordsRequest struct {
	ChainId          string             `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty" yaml:"chain_id"`
	DelegatorAddress string             `protobuf:"bytes,2,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	Pagination       *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryWithdrawalRecordsRequest) Reset()         { *m = QueryWithdrawalRecordsRequest{} }
func (m *QueryWithdrawalRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWithdrawalRecordsRequest) ProtoMessage()    {}
func (*QueryWithdrawalRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{8}
}
func (m *QueryWithdrawalRecordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWithdrawalRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWithdrawalRecordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWithdrawalRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithdrawalRecordsRequest.Merge(m, src)
}
func (m *QueryWithdrawalRecordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWithdrawalRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithdrawalRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithdrawalRecordsRequest proto.InternalMessageInfo

func (m *QueryWithdrawalRecordsRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *QueryWithdrawalRecordsRequest) GetDelegatorAddress() string {
	if m != nil {
		return m.DelegatorAddress
	}
	return ""
}

func (m *QueryWithdrawalRecordsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryWithdrawalRecordsResponse struct {
	Withdrawals []WithdrawalRecord  `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryWithdrawalRecordsResponse) Reset()         { *m = QueryWithdrawalRecordsResponse{} }
func (m *QueryWithdrawalRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWithdrawalRecordsResponse) ProtoMessage()    {}
func (*QueryWithdrawalRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8e4d79429548821, []int{9}
}
func (m *QueryWithdrawalRecordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWithdrawalRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWithdrawalRecordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWithdrawalRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithdrawalRecordsResponse.Merge(m, src)
}
func (m *QueryWithdrawalRecordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWithdrawalRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithdrawalRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithdrawalRecordsResponse proto.InternalMessageInfo

func (m *QueryWithdrawalRecordsResponse) GetWithdrawals() []WithdrawalRecord {
	if m != nil {
		return m.Withdrawals
	}
	return nil
}

func (m *QueryWithdrawalRecordsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryZonesInfoRequest)(nil), "quicksilver.interchainstaking.v1.QueryZonesInfoRequest")
	proto.RegisterType((*QueryZonesInfoResponse)(nil), "quicksilver.interchainstaking.v1.QueryZonesInfoResponse")
	proto.RegisterType((*QueryDepositAccountForChainRequest)(nil), "quicksilver.interchainstaking.v1.QueryDepositAccountForChainRequest")
	proto.RegisterType((*QueryDepositAccountForChainResponse)(nil), "quicksilver.interchainstaking.v1.QueryDepositAccountForChainResponse")
	proto.RegisterType((*QueryDelegatorIntentRequest)(nil), "quicksilver.interchainstaking.v1.QueryDelegatorIntentRequest")
	proto.RegisterType((*QueryDelegatorIntentResponse)(nil), "quicksilver.interchainstaking.v1.QueryDelegatorIntentResponse")
	proto.RegisterType((*QueryDelegationsRequest)(nil), "quicksilver.interchainstaking.v1.QueryDelegationsRequest")
	proto.RegisterType((*QueryDelegationsResponse)(nil), "quicksilver.interchainstaking.v1.QueryDelegationsResponse")
	proto.RegisterType((*QueryWithdrawalRecordsRequest)(nil), "quicksilver.interchainstaking.v1.QueryWithdrawalRecordsRequest")
	proto.RegisterType((*QueryWithdrawalRecordsResponse)(nil), "quicksilver.interchainstaking.v1.QueryWithdrawalRecordsResponse")
}

func init() {
	proto.RegisterFile("quicksilver/interchainstaking/v1/query.proto", fileDescriptor_c8e4d79429548821)
}

var fileDescriptor_c8e4d79429548821 = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x4f, 0x3b, 0x45,
	0x14, 0xef, 0x50, 0xbf, 0x5f, 0x65, 0x9a, 0x08, 0x8c, 0x20, 0xb5, 0xe2, 0x42, 0xd6, 0x44, 0xd4,
	0xc0, 0x6e, 0x8a, 0xc6, 0x1f, 0x44, 0x11, 0x2a, 0xd4, 0xd4, 0x93, 0xae, 0x24, 0x84, 0x7a, 0x68,
	0xa6, 0xdd, 0x71, 0x99, 0x50, 0x66, 0xca, 0xce, 0xb4, 0x58, 0x09, 0x07, 0xfd, 0x0b, 0x34, 0xfa,
	0x2f, 0x78, 0xf6, 0xe2, 0xdd, 0x93, 0x09, 0x89, 0x1e, 0x88, 0x7a, 0xf0, 0xd4, 0x18, 0xf0, 0xe2,
	0x51, 0xee, 0x26, 0x66, 0x67, 0x67, 0x4b, 0x7f, 0xc1, 0x96, 0xd5, 0x44, 0x6f, 0xcb, 0xcc, 0x7b,
	0x9f, 0xf7, 0xf9, 0xbc, 0x79, 0xef, 0x53, 0xe0, 0xca, 0x71, 0x93, 0xd6, 0x0e, 0x05, 0xad, 0xb7,
	0x88, 0x6f, 0x53, 0x26, 0x89, 0x5f, 0x3b, 0xc0, 0x94, 0x09, 0x89, 0x0f, 0x29, 0xf3, 0xec, 0x56,
	0xde, 0x3e, 0x6e, 0x12, 0xbf, 0x6d, 0x35, 0x7c, 0x2e, 0x39, 0x5a, 0xea, 0x89, 0xb6, 0x86, 0xa2,
	0xad, 0x56, 0x3e, 0x37, 0xeb, 0x71, 0x8f, 0xab, 0x60, 0x3b, 0xf8, 0x0a, 0xf3, 0x72, 0x4f, 0xd5,
	0xb8, 0x38, 0xe2, 0xa2, 0x12, 0x5e, 0x84, 0x7f, 0xe8, 0xab, 0x05, 0x8f, 0x73, 0xaf, 0x4e, 0x6c,
	0xdc, 0xa0, 0x36, 0x66, 0x8c, 0x4b, 0x2c, 0x29, 0x67, 0xd1, 0xed, 0x8b, 0x61, 0xac, 0x5d, 0xc5,
	0x82, 0x84, 0x4c, 0xec, 0x56, 0xbe, 0x4a, 0x24, 0xce, 0xdb, 0x0d, 0xec, 0x51, 0xa6, 0x82, 0x75,
	0xac, 0x15, 0x2b, 0xc5, 0x23, 0x8c, 0x08, 0xaa, 0xb1, 0xcd, 0x0a, 0x9c, 0x7b, 0x3f, 0x40, 0x2c,
	0x73, 0x46, 0x44, 0x89, 0x7d, 0xc4, 0x1d, 0x72, 0xdc, 0x24, 0x42, 0xa2, 0x22, 0x84, 0x37, 0xe0,
	0x59, 0xb0, 0x04, 0x9e, 0xcf, 0xac, 0x3d, 0x67, 0x69, 0xd6, 0x01, 0x13, 0x2b, 0xec, 0x89, 0x66,
	0x62, 0xbd, 0x87, 0x3d, 0xa2, 0x73, 0x9d, 0x9e, 0x4c, 0xf3, 0x6b, 0x00, 0x9f, 0x1c, 0xac, 0x20,
	0x1a, 0x9c, 0x09, 0x82, 0x0a, 0xf0, 0xc1, 0x27, 0xc1, 0x61, 0x16, 0x2c, 0xa5, 0x15, 0x7a, 0x5c,
	0x63, 0xad, 0x00, 0xa3, 0xf0, 0xc8, 0x79, 0x67, 0x31, 0xe5, 0x84, 0xa9, 0xe8, 0x9d, 0x3e, 0x9a,
	0x13, 0x8a, 0xe6, 0x72, 0x2c, 0xcd, 0x90, 0x40, 0x1f, 0xcf, 0x5d, 0x68, 0x2a, 0x9a, 0xdb, 0xa4,
	0xc1, 0x05, 0x95, 0x5b, 0xb5, 0x1a, 0x6f, 0x32, 0x59, 0xe4, 0xfe, 0xdb, 0x01, 0x87, 0xa8, 0x2b,
	0x16, 0x7c, 0x4c, 0x71, 0xaa, 0x50, 0x57, 0xf5, 0x64, 0xb2, 0xf0, 0xc4, 0x75, 0x67, 0x71, 0xaa,
	0x8d, 0x8f, 0xea, 0xeb, 0x66, 0x74, 0x63, 0x3a, 0x8f, 0xaa, 0xcf, 0x92, 0x6b, 0x7e, 0x0a, 0xe0,
	0xb3, 0x77, 0xc2, 0xea, 0x56, 0x94, 0xe1, 0xbc, 0x1b, 0x46, 0x54, 0x70, 0x18, 0x52, 0xc1, 0xae,
	0xeb, 0x13, 0x21, 0x74, 0x19, 0xf3, 0xba, 0xb3, 0x68, 0x84, 0x65, 0x6e, 0x09, 0x34, 0x9d, 0x39,
	0xb7, 0xaf, 0xc8, 0x96, 0x3e, 0xff, 0x0a, 0xc0, 0xa7, 0x35, 0x87, 0x3a, 0xf1, 0xb0, 0xe4, 0x7e,
	0x89, 0x49, 0xc2, 0x64, 0x42, 0x4d, 0x68, 0x07, 0xce, 0xb8, 0x11, 0x52, 0x97, 0xe5, 0x84, 0x4a,
	0xcc, 0xfe, 0xf4, 0xed, 0xea, 0xac, 0x6e, 0xbe, 0x2e, 0xff, 0x81, 0xf4, 0x29, 0xf3, 0x9c, 0xe9,
	0x6e, 0x4a, 0x44, 0x8b, 0xc2, 0x85, 0xd1, 0xac, 0x74, 0x4b, 0x4a, 0xf0, 0x21, 0x55, 0x27, 0x7a,
	0xf8, 0xf2, 0xf1, 0xe3, 0x31, 0x08, 0xa5, 0x01, 0xcc, 0x2f, 0x00, 0x9c, 0xef, 0xad, 0x15, 0xec,
	0x56, 0x52, 0xf5, 0xc5, 0x11, 0x03, 0x97, 0x64, 0x2f, 0x7e, 0x00, 0x30, 0x3b, 0xcc, 0x49, 0x6b,
	0xdf, 0x85, 0x19, 0xf7, 0xe6, 0x58, 0xef, 0xc7, 0xca, 0xd8, 0x0d, 0xa0, 0x9c, 0xe9, 0x2d, 0xe9,
	0x85, 0x41, 0xd3, 0x30, 0x2d, 0x5b, 0x75, 0xc5, 0x39, 0xed, 0x04, 0x9f, 0x03, 0xdb, 0x93, 0x4e,
	0xbe, 0x3d, 0x1d, 0x00, 0x9f, 0x51, 0x6a, 0xf6, 0xa8, 0x3c, 0x70, 0x7d, 0x7c, 0x82, 0xeb, 0x0e,
	0xa9, 0x71, 0xdf, 0x15, 0xff, 0xed, 0x94, 0x0d, 0x3c, 0x57, 0x3a, 0xf1, 0x73, 0x7d, 0x0f, 0xa0,
	0x71, 0x9b, 0xc0, 0xee, 0x0e, 0x67, 0x4e, 0xba, 0x97, 0xd1, 0xa3, 0xad, 0xc5, 0x3f, 0xda, 0x20,
	0x62, 0xf4, 0x74, 0x3d, 0x60, 0xff, 0x9a, 0xcd, 0xad, 0x7d, 0x07, 0xe1, 0x03, 0xa5, 0x03, 0x7d,
	0x03, 0xe0, 0x64, 0xe0, 0xa7, 0x81, 0x25, 0x0b, 0xf4, 0x6a, 0x3c, 0xcf, 0x91, 0xbf, 0x13, 0xb9,
	0xd7, 0xee, 0x9f, 0x18, 0xd2, 0x32, 0xed, 0xcf, 0x7e, 0xfe, 0xfd, 0xcb, 0x89, 0x17, 0xd0, 0xb2,
	0x1d, 0xfb, 0x9b, 0x15, 0x7a, 0xfd, 0x1f, 0x00, 0x3e, 0xde, 0xef, 0xa3, 0x68, 0x7b, 0xcc, 0xea,
	0x77, 0xba, 0x7a, 0x6e, 0xe7, 0x1f, 0xa2, 0x68, 0x41, 0xef, 0x2a, 0x41, 0xdb, 0xa8, 0x30, 0xa6,
	0x20, 0xfb, 0x34, 0x9a, 0xfb, 0x33, 0xbb, 0x6b, 0xea, 0x7a, 0x6e, 0xff, 0x04, 0x70, 0x6a, 0xc0,
	0xce, 0xd0, 0x9b, 0x63, 0xd3, 0x1c, 0xe5, 0xf3, 0xb9, 0x8d, 0xa4, 0xe9, 0x5a, 0x5e, 0x45, 0xc9,
	0xdb, 0x47, 0x7b, 0x89, 0xe4, 0x45, 0xab, 0x1c, 0x5a, 0xb2, 0x7d, 0x3a, 0xb4, 0xdc, 0x67, 0xe8,
	0x47, 0x00, 0x33, 0x3d, 0x6e, 0x88, 0x5e, 0xbf, 0x1f, 0xe1, 0x1e, 0x57, 0xcf, 0xad, 0x27, 0x49,
	0xd5, 0x3a, 0x8b, 0x4a, 0xe7, 0x26, 0xda, 0x48, 0xae, 0x53, 0xd1, 0xff, 0x0b, 0xc0, 0xb9, 0x60,
	0xea, 0x87, 0x1c, 0x03, 0xbd, 0x35, 0x26, 0xbb, 0xdb, 0xcc, 0x34, 0xb7, 0x99, 0x1c, 0x40, 0x8b,
	0xc4, 0x4a, 0xe4, 0x87, 0x68, 0x3f, 0x81, 0xc8, 0x1b, 0x63, 0xaa, 0xf8, 0x21, 0xec, 0xc8, 0xe7,
	0xfc, 0x05, 0xc0, 0x99, 0xff, 0xa5, 0xf6, 0x37, 0x94, 0xf6, 0x57, 0xd0, 0xcb, 0xf1, 0xda, 0x87,
	0xa5, 0x16, 0xca, 0xe7, 0x97, 0x06, 0xb8, 0xb8, 0x34, 0xc0, 0x6f, 0x97, 0x06, 0xf8, 0xfc, 0xca,
	0x48, 0x5d, 0x5c, 0x19, 0xa9, 0x5f, 0xaf, 0x8c, 0x54, 0x79, 0xd3, 0xa3, 0xf2, 0xa0, 0x59, 0xb5,
	0x6a, 0xfc, 0xc8, 0xa6, 0xcc, 0x23, 0xac, 0x49, 0x65, 0x7b, 0xb5, 0xda, 0xa4, 0x75, 0xb7, 0xaf,
	0xd2, 0xc7, 0x23, 0x6a, 0xc9, 0x76, 0x83, 0x88, 0xea, 0x43, 0xf5, 0x4f, 0xf9, 0x4b, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x11, 0xc4, 0x5a, 0x3f, 0x91, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ZoneInfos provides meta data on connected zones.
	ZoneInfos(ctx context.Context, in *QueryZonesInfoRequest, opts ...grpc.CallOption) (*QueryZonesInfoResponse, error)
	// DepositAccount provides data on the deposit address for a connected zone.
	DepositAccount(ctx context.Context, in *QueryDepositAccountForChainRequest, opts ...grpc.CallOption) (*QueryDepositAccountForChainResponse, error)
	// DelegatorIntent provides data on the intent of the delegator for the given
	// zone.
	DelegatorIntent(ctx context.Context, in *QueryDelegatorIntentRequest, opts ...grpc.CallOption) (*QueryDelegatorIntentResponse, error)
	// Delegations provides data on the delegations for the given zone.
	Delegations(ctx context.Context, in *QueryDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegationsResponse, error)
	// WithdrawalRecords provides data on the active withdrawals.
	ZoneWithdrawalRecords(ctx context.Context, in *QueryWithdrawalRecordsRequest, opts ...grpc.CallOption) (*QueryWithdrawalRecordsResponse, error)
	// WithdrawalRecords provides data on the active withdrawals.
	WithdrawalRecords(ctx context.Context, in *QueryWithdrawalRecordsRequest, opts ...grpc.CallOption) (*QueryWithdrawalRecordsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ZoneInfos(ctx context.Context, in *QueryZonesInfoRequest, opts ...grpc.CallOption) (*QueryZonesInfoResponse, error) {
	out := new(QueryZonesInfoResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/ZoneInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DepositAccount(ctx context.Context, in *QueryDepositAccountForChainRequest, opts ...grpc.CallOption) (*QueryDepositAccountForChainResponse, error) {
	out := new(QueryDepositAccountForChainResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/DepositAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegatorIntent(ctx context.Context, in *QueryDelegatorIntentRequest, opts ...grpc.CallOption) (*QueryDelegatorIntentResponse, error) {
	out := new(QueryDelegatorIntentResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/DelegatorIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Delegations(ctx context.Context, in *QueryDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegationsResponse, error) {
	out := new(QueryDelegationsResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/Delegations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ZoneWithdrawalRecords(ctx context.Context, in *QueryWithdrawalRecordsRequest, opts ...grpc.CallOption) (*QueryWithdrawalRecordsResponse, error) {
	out := new(QueryWithdrawalRecordsResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/ZoneWithdrawalRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WithdrawalRecords(ctx context.Context, in *QueryWithdrawalRecordsRequest, opts ...grpc.CallOption) (*QueryWithdrawalRecordsResponse, error) {
	out := new(QueryWithdrawalRecordsResponse)
	err := c.cc.Invoke(ctx, "/quicksilver.interchainstaking.v1.Query/WithdrawalRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ZoneInfos provides meta data on connected zones.
	ZoneInfos(context.Context, *QueryZonesInfoRequest) (*QueryZonesInfoResponse, error)
	// DepositAccount provides data on the deposit address for a connected zone.
	DepositAccount(context.Context, *QueryDepositAccountForChainRequest) (*QueryDepositAccountForChainResponse, error)
	// DelegatorIntent provides data on the intent of the delegator for the given
	// zone.
	DelegatorIntent(context.Context, *QueryDelegatorIntentRequest) (*QueryDelegatorIntentResponse, error)
	// Delegations provides data on the delegations for the given zone.
	Delegations(context.Context, *QueryDelegationsRequest) (*QueryDelegationsResponse, error)
	// WithdrawalRecords provides data on the active withdrawals.
	ZoneWithdrawalRecords(context.Context, *QueryWithdrawalRecordsRequest) (*QueryWithdrawalRecordsResponse, error)
	// WithdrawalRecords provides data on the active withdrawals.
	WithdrawalRecords(context.Context, *QueryWithdrawalRecordsRequest) (*QueryWithdrawalRecordsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ZoneInfos(ctx context.Context, req *QueryZonesInfoRequest) (*QueryZonesInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneInfos not implemented")
}
func (*UnimplementedQueryServer) DepositAccount(ctx context.Context, req *QueryDepositAccountForChainRequest) (*QueryDepositAccountForChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositAccount not implemented")
}
func (*UnimplementedQueryServer) DelegatorIntent(ctx context.Context, req *QueryDelegatorIntentRequest) (*QueryDelegatorIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegatorIntent not implemented")
}
func (*UnimplementedQueryServer) Delegations(ctx context.Context, req *QueryDelegationsRequest) (*QueryDelegationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delegations not implemented")
}
func (*UnimplementedQueryServer) ZoneWithdrawalRecords(ctx context.Context, req *QueryWithdrawalRecordsRequest) (*QueryWithdrawalRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneWithdrawalRecords not implemented")
}
func (*UnimplementedQueryServer) WithdrawalRecords(ctx context.Context, req *QueryWithdrawalRecordsRequest) (*QueryWithdrawalRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawalRecords not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ZoneInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryZonesInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ZoneInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/ZoneInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ZoneInfos(ctx, req.(*QueryZonesInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DepositAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDepositAccountForChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DepositAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/DepositAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DepositAccount(ctx, req.(*QueryDepositAccountForChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegatorIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegatorIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegatorIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/DelegatorIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegatorIntent(ctx, req.(*QueryDelegatorIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Delegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Delegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/Delegations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Delegations(ctx, req.(*QueryDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ZoneWithdrawalRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWithdrawalRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ZoneWithdrawalRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/ZoneWithdrawalRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ZoneWithdrawalRecords(ctx, req.(*QueryWithdrawalRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WithdrawalRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWithdrawalRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WithdrawalRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quicksilver.interchainstaking.v1.Query/WithdrawalRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WithdrawalRecords(ctx, req.(*QueryWithdrawalRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quicksilver.interchainstaking.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZoneInfos",
			Handler:    _Query_ZoneInfos_Handler,
		},
		{
			MethodName: "DepositAccount",
			Handler:    _Query_DepositAccount_Handler,
		},
		{
			MethodName: "DelegatorIntent",
			Handler:    _Query_DelegatorIntent_Handler,
		},
		{
			MethodName: "Delegations",
			Handler:    _Query_Delegations_Handler,
		},
		{
			MethodName: "ZoneWithdrawalRecords",
			Handler:    _Query_ZoneWithdrawalRecords_Handler,
		},
		{
			MethodName: "WithdrawalRecords",
			Handler:    _Query_WithdrawalRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quicksilver/interchainstaking/v1/query.proto",
}

func (m *QueryZonesInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryZonesInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryZonesInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryZonesInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryZonesInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryZonesInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Zones) > 0 {
		for iNdEx := len(m.Zones) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Zones[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDepositAccountForChainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDepositAccountForChainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDepositAccountForChainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDepositAccountForChainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDepositAccountForChainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDepositAccountForChainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositAccountAddress) > 0 {
		i -= len(m.DepositAccountAddress)
		copy(dAtA[i:], m.DepositAccountAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DepositAccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegatorIntentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegatorIntentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegatorIntentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegatorIntentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegatorIntentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegatorIntentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Intent != nil {
		{
			size, err := m.Intent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Tvl != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Tvl))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Delegations) > 0 {
		for iNdEx := len(m.Delegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryWithdrawalRecordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWithdrawalRecordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWithdrawalRecordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWithdrawalRecordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWithdrawalRecordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWithdrawalRecordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Withdrawals) > 0 {
		for iNdEx := len(m.Withdrawals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Withdrawals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryZonesInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryZonesInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Zones) > 0 {
		for _, e := range m.Zones {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDepositAccountForChainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDepositAccountForChainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DepositAccountAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDelegatorIntentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDelegatorIntentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Intent != nil {
		l = m.Intent.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDelegationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDelegationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Delegations) > 0 {
		for _, e := range m.Delegations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Tvl != 0 {
		n += 1 + sovQuery(uint64(m.Tvl))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWithdrawalRecordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWithdrawalRecordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Withdrawals) > 0 {
		for _, e := range m.Withdrawals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryZonesInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryZonesInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryZonesInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryZonesInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryZonesInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryZonesInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zones", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Zones = append(m.Zones, Zone{})
			if err := m.Zones[len(m.Zones)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDepositAccountForChainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDepositAccountForChainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDepositAccountForChainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDepositAccountForChainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDepositAccountForChainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDepositAccountForChainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegatorIntentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegatorIntentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegatorIntentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegatorIntentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegatorIntentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegatorIntentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Intent == nil {
				m.Intent = &DelegatorIntent{}
			}
			if err := m.Intent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegations = append(m.Delegations, Delegation{})
			if err := m.Delegations[len(m.Delegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tvl", wireType)
			}
			m.Tvl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tvl |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWithdrawalRecordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWithdrawalRecordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWithdrawalRecordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWithdrawalRecordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWithdrawalRecordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWithdrawalRecordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdrawals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdrawals = append(m.Withdrawals, WithdrawalRecord{})
			if err := m.Withdrawals[len(m.Withdrawals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
