run:
  tests: true
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  skip-dirs:
    - osmosis-types/*

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    - nolintlint

exclude-rules:
  - linters:
      - nolintlint
    text: "should be written without leading space"
